// <auto-generated />
using System;
using ICMarkets.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICMarkets.Infrastructure.Migrations
{
    [DbContext(typeof(IcMarketsDbContext))]
    [Migration("20260618180643_updateEvent")]
    partial class updateEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ICMarkets.Domain.BlockchainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BaseFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockchainIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HighFeePerKb")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HighGasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HighPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastForkHash")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastForkHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LowFeePerKb")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LowGasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LowPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediumFeePerKb")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediumGasPrice")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MediumPriorityFee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PeerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnconfirmedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainIdentifier")
                        .IsUnique();

                    b.ToTable("blockchain", (string)null);
                });

            modelBuilder.Entity("ICMarkets.Domain.EventEnvelope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "OccurredAt")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
